using System;
using System.Text;

namespace NUnit.That.Resharper_v10.Plugin.TabManager
{
    public class OutputTabManager: BasicTabManager
    {
        public OutputTabManager OutputHeader()
        {
            StringBuilder header = new StringBuilder();
            header.AppendLine("The report generated by R# plugin NUnit.That.Resharper.Plugin (https://github.com/constructor-igor/NUnit.That.Resharper.Plugin).");
            header.AppendLine("Can be installed from https://resharper-plugins.jetbrains.com/packages/NUnit.That.Resharper_v10.Plugin/");
            OutputLine(header.ToString());
            return this;
        }

        public OutputTabManager(): 
            base(new Guid("D556397E-D292-4707-B924-5FFFD20802C7"), "NUnit.That")
        {
        }
    }
}